const Database1 = [
  {
    name: "Ibelahi Chinedu",
    gender: "male",
    score: "90",
    rank: "2990",
    pos: "1",
    img: "/images/m4.png",
  },
  {
    name: "Ijeoma Mboranye",
    gender: "female",
    score: "91",
    rank: "2970",
    pos: "2",
    img: "/images/df.png",
  },
  {
    name: "Favor Anyaegbu",
    gender: "female",
    score: "85",
    rank: "2950",
    pos: "3",
    img: "/images/f4.png",
  },
  {
    name: "Jonathan Amaobi",
    gender: "male",
    score: "75",
    rank: "2500",
    pos: "4",
    img: "/images/ronaldo.png",
  },
  {
    name: "Arnold Ngowi",
    gender: "male",
    score: "69",
    rank: "2200",
    pos: "5",
    img: "/images/m3.png",
  },
  {
    name: "Chioma Ugwuodo",
    gender: "female",
    score: "50",
    rank: "1500",
    pos: "6",
    img: "/images/df.png",
  },
];
export default Database1;
